name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "pypy-3.8"
          - "pypy-3.9"

    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      
      - name: Remove existing clavrs.exe if present
        shell: pwsh
        run: |
          $file = "LocalDB/db/clavrs.exe"
          if (Test-Path $file) {
            Remove-Item $file -Force
            Write-Host "Deleted existing clavrs.exe"
          } else {
            Write-Host "clavrs.exe does not exist, nothing to delete"
          }

      - name: Download latest clavrs.exe release (versioned file)
        shell: pwsh
        run: |
          $release = Invoke-RestMethod -Uri https://api.github.com/repos/cydian-ger/clavrs/releases/latest
          # Find asset whose name matches clavrs-*.exe
          $asset = $release.assets | Where-Object { $_.name -match '^clavrs-.*\.exe$' } | Select-Object -First 1
          if (-not $asset) {
            Write-Error "No matching clavrs executable found in release assets!"
            exit 1
          }
          Write-Host "Downloading $($asset.name) from $($asset.browser_download_url)"
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile LocalDB/db/clavrs.exe


      - name: Run unittests
        run: python -m test.run_tests
